### ISSUE TITLE
Boskos hard-down 

### ISSUE THREAD

**Issue by howardjohn** [sebastienvas/istio-testing#3601]
All Boskos jobs have been failing for a while now. Example failure: https://prow.istio.io/view/gs/istio-prow/logs/istio-dual-control-plane-upgrade-1.9-master/1445297725049409536

We used to have monitoring of boskos at http://velodrome.istio.io/ but its failing now

**Comment by howardjohn** [comment]
`Permission denied to list services for consumer container`. Maybe broken since the WI changes? https://github.com/istio/test-infra/pull/3577

First failure 9/26 but that was merged 9/24 so it doesn't exactly line up. fyi @cjwagner

**Comment by howardjohn** [comment]
cc @stewartbutler

**Comment by cjwagner** [comment]
> Permission denied to list services for consumer container

Where are you seeing that error? I'm seeing the following error from `boskos-mason` instead:

> E1002 08:08:59.086475       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *crds.DRLCObject: Get https://10.0.0.1:443/apis/boskos.k8s.io/v1/namespaces/boskos/dynamicresourcelifecycles?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused

------

> Maybe broken since the WI changes? #3577

Its possible, but that change removed the old credentials and I confirmed that the deployments were still functioning properly, so I'm pretty sure WI was working at that point at least.

**Comment by howardjohn** [comment]
> Where are you seeing that error? I'm seeing the following error from boskos-mason instead:


I saw it in boskos-0 pod. Maybe its not the underlying issue. There was also some errors about failing to fetch `gcp-project` resource. Not sure which is the root cause and what is a symptom

**Comment by chizhg** [comment]
I was chatting with @richardwxn the other day on this issue and it was due to the internal bug 193694780#comment12.
There we switched Istio Prow jobs to run with a different service account, which didn't have permissions to clean up the GCP projects.

Now the issue should have been fixed after I granted the permission - https://prow.istio.io/?job=istio-dual-control-plane-upgrade-1.9-master, please reopen if you are still seeing it or any other issues related to Boskos.
